### PR TITLE
modernize framework for swift 5 and Xcode 11

### PR DESCRIPTION
**Pull request by MadeByDouglas**
Can you check and make sure I didnt break anything?

There were some differences between yours and the original one, and I wasn't sure what to do with the old bridging header references so I just deleted them. It seems like they aren't needed anymore.

Everything builds now with no warnings.

### CODE REVIEW

**Comment by cbess** [comment]
This is quite a few changes. I'll update it to Swift 5 and review the changes as well.

**Comment by cbess** [comment]
Thanks for the reminder to update it for Xcode 11.2 and Swift 5, but when I ran the "converter" it had nothing to convert. The code was Swift 5 compatible.

**Comment by MadeByDouglas** [comment]
True but you need to run it and then change the target from swift 3 to 5 so when people open it for first time it doesn’t throw a bunch of warnings; then those get saved to the Xcode proj file

**Comment by cbess** [comment]
Sorry, I'm not 100% understanding. I ran it, in the simulator, updated the target to use Swift `5` (it was using `4`, not `3`), and I only see two warnings in the log. I think I'm missing something.

**Comment by MadeByDouglas** [comment]
Hmm for me when I cloned it was using swift 3 and gave a warning saying: “use of this version of swift unsupported” etc.

You’re right though, once you flip the switch nothing really changes and its all happy.

Also, did you check for both the framework and the sample project? It needs to be done to both.

Anyway, made some videos just showing what I did, although the changes were already made by the time I filmed it of course.
https://relay.how/question/d053aef0-54c8-403e-9de9-b72f23b9ece7


Let me know if we’re on the same page.

**Comment by cbess** [comment]
Thanks for the short videos, they helped me understand more. However, as far as I know, when I started the refactor to use `WKWebView`, I had already set the min. deployment target to `10`, which is why the `podspec` file says `10`.

changed podspec to min `iOS 10`: 
- https://github.com/cbess/RichEditorView/commit/b1c3bd7886cce0eb7af2891f8283fe2ca54c6428#diff-27d6f6e43f92f4b03856a01473a18b48

changed project to min `iOS 10` and converted to Swift 4:
- https://github.com/cbess/RichEditorView/commit/007acbeac212ebc16ffc3ed462c687b24fa47d99

Both change sets are from May of 2018. So, I point that out to ask, which branch or commit are you using in the video, because it was not the latest code.

**Comment by MadeByDouglas** [comment]
Hmm maybe the sample was already at 10, but the framework was at 8

If I get some time I will download a zip of the project again and go through all the stuff where it was at when I downloaded it.

**Pull request closed without merging**
